EXTRN	FUNC4: FAR

DATE SEGMENT PARA PUBLIC 'DATA' ; data segment definition
	ARRAY	DW		1, 2, 3, 4, 5
	LEN		DW		($-ARRAY) / 2	
DATE ENDS

COD SEGMENT PARA PUBLIC 'CODE' ; code segment definition
EXTRN 	FUNC3: NEAR
ASSUME CS: COD, DS: DATE
START PROC FAR		; main procedure definition
	PUSH	DS
	XOR 	AX, AX
	MOV		AX, DATE
	MOV		DS, AX
	
	MOV		BX, OFFSET ARRAY
	MOV		CX, LEN
	
	CALL	FUNC
	
	CALL 	FUNC2
	
	CALL 	FUNC3
	
	CALL	FUNC4
	
	RET				; coming back to DOS
START ENDP 			; end procedure

FUNC PROC NEAR
	PUSH	CX
	XOR		AX, AX
	MOV 	SI, 0
	ITERATE:
		ADD AX, BX[SI]
		INC	SI
		INC SI
		LOOP ITERATE
	POP 	CX
	RET
FUNC ENDP
COD ENDS 			; end segment

COD2 SEGMENT PARA PUBLIC 'CODE'
ASSUME CS: COD2, DS: DATE
FUNC2 PROC FAR
	PUSH	CX
	XOR		AX, AX
	MOV 	SI, 0
	ITERATE2:
		ADD AX, BX[SI]
		INC	SI
		INC	SI
		LOOP ITERATE2
	POP 	CX
	RETF
FUNC2 ENDP
COD2 ENDS
	END START
	